import pygame,model, settings,entity
pygame.init()
screen=pygame.display.set_mode(settings.SIZE)
pygame.mixer_music.load('audio/music/friday_theme.mp3')
# pygame.mixer_music.set_volume(0.1)
# pygame.mixer_music.play(-1)
def risovanie():
    screen.fill([0,0,0])
    model.box1.risyem(screen)
    model.player.risyem(screen)
    model.water.risyem(screen)
    pygame.draw.circle(screen,[0,255,0],[entity.xmovier(model.player,240),entity.ymovier(model.player,200)],10,3)
    pygame.draw.circle(screen,[255,0,0],[200,150],10,3)
    model.inventory.risovanie(screen)
    pygame.display.flip()
